### ISSUE TITLE
"Unexpected usage" error from t.loadForeignModule 

### ISSUE THREAD

**Issue by ischrei** [Azure/monaco-kusto#104]
Unhandled exception, happened 900 times for 85 users in the last week.

Error: Unexpected usage
    at t.loadForeignModule (https://afd.hosting.portal.azure.net/logsextension/az/monaco_editor.d537471f6f5944dd31c1.js:1:185805)
    at https://afd.hosting.portal.azure.net/logsextension/az/monaco_editor.d537471f6f5944dd31c1.js:1:1542856
    at https://logsextension.hosting.portal.azure.net/logsextension/az/bootstrap.9e153e60925e8ba8a711_041f86e38a6bced826a0.js:14:2869
    at N (https://logsextension.hosting.portal.azure.net/logsextension/az/bootstrap.9e153e60925e8ba8a711_041f86e38a6bced826a0.js:14:2903)
    at z (https://logsextension.hosting.portal.azure.net/logsextension/az/bootstrap.9e153e60925e8ba8a711_041f86e38a6bced826a0.js:14:2724)
    at MutationObserver.m (https://logsextension.hosting.portal.azure.net/logsextension/az/bootstrap.9e153e60925e8ba8a711_041f86e38a6bced826a0.js:14:680)

**Comment by lidermanrony** [comment]
looks like an issue that was solved in a later Monaco version. 
https://github.com/microsoft/monaco-editor-webpack-plugin/issues/32

We should probably upgrade monaco (we're using a very old version now) and see if this stops happening.

**Comment by michal-ayash** [comment]
We're still getting this error.. any update?

**Comment by maxburs** [comment]
@michal-ayash are you still seeing this issue?
