### ISSUE TITLE
Cannot read property 'getText' of null

### ISSUE THREAD

**Issue by razronen** [Azure/monaco-kusto#79]
In LogsPortal we get the bellow exception:
It comes from `parseDocumentV2` method.

TypeError: Cannot read property 'getText' of null
    at e.parseDocumentV2 (https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:18:1675235)
    at e.doCompleteV2 (https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:18:1654319)
    at e.doComplete (https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:18:1654220)
    at e.doComplete (https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:18:1680252)
    at t.fmr (https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:4:8369)
    at t._handleMessage (https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:71:32371)
    at Object.handleMessage (https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:71:32004)
    at t._handleMessage (https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:71:30273)
    at t.handleMessage (https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:71:29841)
    at t.onmessage (https://hosting.onecloud.azure-test.net/logsextension/az/kusto.worker.58fc3e3c6ecf67e57069_28b25f6068a46082d38a.js:71:32083) at e.parseDocumentV2

**Comment by rogarfel** [comment]
we are using:     "monaco-editor": "0.15.4",
The exception still happen

**Comment by lidermanrony** [comment]
Hi folks.
can you please provide:
1. repro steps
2. impact on user
